// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nodes} from '../models';
import {main} from '../models';

export function AddNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function DownloadObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function GetAllS3NodesInfo():Promise<Array<nodes.Node>>;

export function GetNodeBucketInfo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<nodes.NodeBucketInfo>>;

export function GetObjectInfo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.ObjectInfo>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<main.ObjectInfo>>;

export function NewS3Client(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.S3Manager>;

export function UploadObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
