// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['S3Manager']['AddNode'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadObject(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['S3Manager']['DownloadObject'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAllS3NodesInfo() {
  return window['go']['main']['S3Manager']['GetAllS3NodesInfo']();
}

export function GetNodeBucketInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['S3Manager']['GetNodeBucketInfo'](arg1, arg2, arg3, arg4);
}

export function GetObjectInfo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['S3Manager']['GetObjectInfo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListObjects(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['S3Manager']['ListObjects'](arg1, arg2, arg3, arg4, arg5);
}

export function NewS3Client(arg1, arg2, arg3, arg4) {
  return window['go']['main']['S3Manager']['NewS3Client'](arg1, arg2, arg3, arg4);
}

export function UploadObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['S3Manager']['UploadObject'](arg1, arg2, arg3, arg4, arg5);
}
